--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/angga7togk/ChatPerWorld
build-by-default: true
branches:
- main
projects:
  ChatPerWorld:
    path: ""
  icon:
    path: "icon.png"
...
