name: ChatPerWorld
main: angga7togk\chatperworld\ChatPerWorld
version: 2.1.0
api: 5.0.0
author: Angga7Togk
description: "To Split Words In Specific Word"

commands:
  globalchat:
    description: "enable or disable GlobalChat Mode"
    permission: chatperworld.globalchat.command
    aliases: [gchat]

permissions:
  chatperworld.globalchat.command:
    default: op